# Generated by Django 4.2.7 on 2025-11-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_image', models.ImageField(blank=True, upload_to='retina_images/processed/')),
                ('microaneurysms_count', models.IntegerField(default=0)),
                ('lesion_area', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Microaneurysm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('diameter', models.FloatField()),
                ('confidence', models.FloatField()),
                ('detection_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microaneurysms', to='detection.detectionresult')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
    ]
