# Generated by Django 4.2.7 on 2025-11-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='retina_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detection_result', to='images.retinaimage'),
        ),
    ]
