# Generated by Django 4.2.7 on 2025-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='processed_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='retina_images/processed/'),
        ),
    ]
