# Generated by Django 4.2.7 on 2026-02-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("clinician", "Clinician"), ("admin", "Administrator")],
                default="clinician",
                max_length=20,
            ),
        ),
    ]
