# Generated by Django 4.2.7 on 2026-02-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("clinician", "Clinician"),
                    ("researcher", "Researcher"),
                    ("admin", "Administrator"),
                ],
                default="clinician",
                max_length=20,
            ),
        ),
    ]
