# Generated by Django 4.2.7 on 2025-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('report_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], default='PDF', max_length=10)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(upload_to='reports/')),
                ('parameters', models.JSONField(default=dict)),
            ],
        ),
    ]
