# Generated by Django 5.2.10 on 2026-01-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retinaimage',
            name='image_type',
            field=models.CharField(choices=[('FUNDUS', 'Fundus'), ('NON_FUNDUS', 'Non-Fundus'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12),
        ),
    ]
