# Generated by Django 4.2.7 on 2025-11-11 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_initial'),
        ('tracking', '0001_initial'),
        ('detection', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='images.patient'),
        ),
        migrations.AddField(
            model_name='progressiondata',
            name='detection_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.detectionresult'),
        ),
        migrations.AddField(
            model_name='progressiondata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_data', to='images.patient'),
        ),
        migrations.AddField(
            model_name='progressiondata',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.patientvisit'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='images.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='patientvisit',
            unique_together={('patient', 'visit_number')},
        ),
    ]
